language: node_js
env: CI=true
node_js:
  - "6.7.0"
before_install:
  - "gem update bundler"
  - "gem update --system"
  - "gem --version"
  - "rvm reinstall ruby-head --binary"
install: 
  - "npm install"
  - "npm install bower -g"
  - "bower install"  
  - ""
  - "gem install scss_lint"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
- "gulp"
- "gulp test"